import Link from 'next/link';

export default function Home() {
  return (
    <div className="bg-white p-8 rounded-xl shadow-sm border mt-8 text-center max-w-3xl mx-auto space-y-6">
      <h1 className="text-4xl font-extrabold text-indigo-600">Welcome to Cafteriaflow Dashboard</h1>
      <p className="text-lg text-gray-500">
        Manage your multi-tenant WhatsApp ordering AI across multiple restaurants.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
        <Link href="/onboarding" className="p-6 border rounded-lg hover:border-indigo-500 hover:shadow-md transition bg-gray-50 text-left cursor-pointer">
          <h3 className="text-lg font-bold text-gray-900">Onboard New Restaurant</h3>
          <p className="mt-2 text-sm text-gray-500">Create a tenant profile and scan the Evolution WhatsApp QR code to connect the number.</p>
        </Link>

        <Link href="/menu" className="p-6 border rounded-lg hover:border-indigo-500 hover:shadow-md transition bg-gray-50 text-left cursor-pointer">
          <h3 className="text-lg font-bold text-gray-900">Menu Editor</h3>
          <p className="mt-2 text-sm text-gray-500">Configure your restaurant's items and categories that the AI will use to recommend and generate orders.</p>
        </Link>

        <Link href="/orders" className="p-6 border rounded-lg hover:border-indigo-500 hover:shadow-md transition bg-gray-50 text-left cursor-pointer md:col-span-2">
          <h3 className="text-lg font-bold text-gray-900">Orders & Analytics</h3>
          <p className="mt-2 text-sm text-gray-500">View real-time incoming orders, total revenue metrics, and bot resolution rates generated by NVIDIA NIM.</p>
        </Link>
      </div>
    </div>
  );
}
