ALTER TABLE tenants ADD COLUMN IF NOT EXISTS name VARCHAR DEFAULT 'Unnamed';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS tenant_type VARCHAR DEFAULT 'EVOLUTION';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS phone_number_id VARCHAR;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS waba_id VARCHAR;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS access_token VARCHAR;
ALTER TABLE tenants ALTER COLUMN instance_name DROP NOT NULL;
ALTER TABLE tenants ALTER COLUMN api_key DROP NOT NULL;
